name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

env:
  REGISTRY: cr.yandex/crps1p5u048a00f4o97j
  IMAGE_NAME: testapp
  K8S_NAMESPACE: app
  DEPLOYMENT_NAME: testapp

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::8} .
        docker build -t $REGISTRY/$IMAGE_NAME:latest .

    - name: Run tests
      run: |
        echo "Running tests..."
        # Пример простого теста - проверяем что index.html существует
        if [ -f "index.html" ]; then
          echo "✓ index.html found"
        else
          echo "✗ index.html not found"
          exit 1
        fi

  push-to-registry:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Yandex Container Registry
      run: |
        # Создаем временный файл с JSON ключом
        echo '${{ secrets.YC_SA_KEY }}' > /tmp/key.json
        # Аутентифицируемся
        cat /tmp/key.json | docker login \
          --username json_key \
          --password-stdin \
          cr.yandex

    - name: Build and push Docker image
      run: |
        # Определяем тег
        if [ "${{ github.event_name }}" == "release" ]; then
          IMAGE_TAG="${{ github.event.release.tag_name }}"
        else
          IMAGE_TAG="${GITHUB_SHA::8}"
        fi
        
        echo "Building image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
        
        # Собираем и пушим образ
        docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
        docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        
        # Также пушим latest для обычных коммитов
        if [ "${{ github.event_name }}" == "push" ]; then
          docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
          echo "Pushed latest tag"
        fi

  deploy-to-k8s:
    needs: push-to-registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Deploy to Kubernetes
      run: |
        # Создаем kubeconfig
        cat > kubeconfig.yaml << CONFIG
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${{ secrets.K8S_CA_CERT }}
    server: ${{ secrets.K8S_ENDPOINT }}
  name: cluster
contexts:
- context:
    cluster: cluster
    user: user
  name: context
current-context: context
kind: Config
users:
- name: user
  user:
    token: ${{ secrets.K8S_TOKEN }}
CONFIG

        export KUBECONFIG=kubeconfig.yaml
        
        # Проверяем подключение к кластеру
        echo "Testing cluster connection..."
        kubectl cluster-info
        kubectl get nodes
        
        # Определяем тег образа
        if [ "${{ github.event_name }}" == "release" ]; then
          TAG="${{ github.event.release.tag_name }}"
        else
          TAG="${GITHUB_SHA::8}"
        fi
        
        IMAGE_URL="$REGISTRY/$IMAGE_NAME:$TAG"
        echo "Deploying image: $IMAGE_URL to namespace: $K8S_NAMESPACE"
        
        # Обновляем deployment
        kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE_URL -n $K8S_NAMESPACE
        
        # Ждем обновления
        echo "Waiting for rollout to complete..."
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE --timeout=300s
        
        # Проверяем статус
        echo "Deployment status:"
        kubectl get deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE -o wide
        
        echo "Pods status:"
        kubectl get pods -n $K8S_NAMESPACE -l app=$DEPLOYMENT_NAME

    - name: Verify application health
      run: |
        export KUBECONFIG=kubeconfig.yaml
        
        echo "Verifying application health..."
        
        # Получаем информацию о сервисе
        kubectl get svc -n $K8S_NAMESPACE
        
        # Проверяем поды
        kubectl get pods -n $K8S_NAMESPACE -l app=$DEPLOYMENT_NAME
        
        # Проверяем логи последнего пода
        POD_NAME=$(kubectl get pods -n $K8S_NAMESPACE -l app=$DEPLOYMENT_NAME --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1].metadata.name}')
        echo "Checking logs for pod: $POD_NAME"
        kubectl logs -n $K8S_NAMESPACE $POD_NAME --tail=10
        
        echo "✓ Deployment completed successfully"

  notify-success:
    needs: [build-and-test, push-to-registry, deploy-to-k8s]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify success
      if: needs.build-and-test.result == 'success' && needs.push-to-registry.result == 'success' && needs.deploy-to-k8s.result == 'success'
      run: |
        echo "CI/CD Pipeline completed successfully!"
        echo "Image: $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::8}"
        echo "Deployed to: $K8S_NAMESPACE/$DEPLOYMENT_NAME"

    - name: Notify failure
      if: needs.build-and-test.result == 'failure' || needs.push-to-registry.result == 'failure' || needs.deploy-to-k8s.result == 'failure'
      run: |
        echo "CI/CD Pipeline failed"
        echo "Check the logs for details"
        exit 1
